name: neep
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - hoomd
  - gsd
  - freud
  - fresnel
  - pip:
    - torch
    - torchvision
    - numpy==1.16.1
    - tqdm
    - matplotlib
    - pandas
    - scipy
    - seaborn
    - jupyter
    - ipykernel